# Generated by Django 2.2.8 on 2020-01-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('graphite', 'Graphite'), ('modern', 'Modern'), ('metal', 'Metal'), ('oversize', 'Oversize'), ('modern', 'Modern')], on_delete=django.db.models.deletion.PROTECT, to='products.Category'),
        ),
    ]
