# Generated by Django 2.2.8 on 2020-01-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Graphite', 'Graphite'), ('Modern', 'Modern'), ('Metal', 'Metal'), ('Oversize', 'Oversize'), ('Wood', 'Wood')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Category'),
        ),
    ]
