# Generated by Django 2.2.8 on 2020-01-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200111_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Graphite', 'Graphite'), ('Modern', 'Modern'), ('Metal', 'Metal'), ('Oversize', 'Oversize'), ('Wood', 'Wood')], on_delete=django.db.models.deletion.PROTECT, to='products.Category'),
        ),
    ]
