# Generated by Django 2.2.8 on 2020-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200112_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Graphite', 'Graphite'), ('Modern', 'Modern'), ('Metal', 'Metal'), ('Oversize', 'Oversize'), ('Wood', 'Wood')], default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
